= Contributing

Thanks for your interest in this project!

== Be A Beta Tester

The best way for you to contribute is to test the generator: Take a real OpenAPI specification that you work with in any project you maintain, then generate a client for it with Lily. Try to make all the same requests you normally need and see if they all work. More than likely, you will encounter shortcomings with the generated API. When that happens, open an Issue with the following:

. What did you need Lily to do?
. What did it actually do?
. Were you able to work around the issue or shortcoming, and if so, how?
. Provide a stack trace, if any.
. Provide the OpenAPI specification, or a redacted version, or a similar and minimal reproducer if possible.

There are many feature we know we don't support yet. Don't worry about accidentally telling us something we already know -- this is still useful, as it helps us prioritize which features to implement.

== Submit Code

If you're interesting in contributing code to the project, great! We keep a minimal backlog in our [github project](https://github.com/users/Tomboyo/projects/1) that you can browse to see what work we're looking at in the immediate future. If the backlog is currently empty, please feel free to reach out over email (TomASimmons@gmail.com; that's Tom A Simmons) or by opening an Issue. We definitely have things to do, and we can work together to figure out what is best to get started on.

If you have a sepcific feature in mind, feel free to open an issue describing:

. What feature would you like to implement, and
. What will the generated API look like with that implementation? Write some java code out to demonstrate.

We'll review whether the feature is a good fit for Lily and how best to design the API. We'll also review current best-practices in the ever-evolving codebase (that is, we'll discuss what parts of Lily should be imitated, and what parts should not be imitated).

Thanks again!
