= Lily OAS-To-Java Compiler

Lily is a compiler that consumes OpenAPI (Swagger) specifications and produces Java source code.
It is intended to be an alternative to https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator], which at time of writing is the only option, and substantially more complete than Lily.

== Usage

Please be aware that Lily is in the early stages of development and may not be suitable for production use-cases. Use Lily at your own risk.

To generate sources from an OAS document in your maven project, and the following maven build plugin and dependencies:

```xml
<build>
    <plugins>
        <plugin>
            <groupId>io.github.tomboyo.lily</groupId>
            <artifactId>lily-compiler-maven-plugin</artifactId>
            <version>0.1.6</version>
            <configuration>
                <!-- Any URI to an OAS document, be it https:// or file://. -->
                <uri>https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml</uri>

                <!-- Uncomment to customize the default generated sources directory. -->
                <!-- <outputDir>target/generated-sources</outputDir> -->

                <basePackage>com.exmaple.my.api</basePackage>
            </configuration>
            <executions>
                <execution>
                    <goals>
                        <goal>compile-client</goal>
                    </goals>
                    <phase>generate-sources</phase>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>

 <dependencyManagement>
    <dependencies>
        <!-- BEGIN generated code dependency management -->
        <dependency>
            <groupId>com.fasterxml.jackson</groupId>
            <artifactId>jackson-bom</artifactId>
            <version>2.13.0</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
        <!-- END generated code dependency management -->
    </dependencies>
</dependencyManagement>

<dependencies>
     <!-- BEGIN Generated code dependencies -->
    <dependency>
        <groupId>io.github.tomboyo.lily</groupId>
        <artifactId>lily-http</artifactId>
        <version>0.1.6</version>
    </dependency>
    <dependency>
        <groupId>com.fasterxml.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
        <!-- ZonedDatetime support -->
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jsr310</artifactId>
    </dependency>
    <!-- END Generated code dependencies -->
</dependencies>
```

The generated source code relies on jackson and the lily-http library at runtime, which is why these dependencies are necessary.

These configurations can be stand-alone or embedded in a larger project.

For examples of how to use the generated API and what features are supported, please refer to the `modules/example/src/test/java` directory, which contains some basic examples of what the API is capable of.

== Goals

. Generate java source code directly from an OAS document within a java build pipeline (e.g. integrated with Maven or Gradle).
. Support OAS v3.
. Target Java 17.
. Help end-users work around incorrect or incomplete schema specifications so that they can make progress while awaiting upstream fixes.
. Expose a high-level API to guide the user through API interactions.
. Ensure that whenever possible, generated source code is compatible with user code between API specification revisions. In other words: "If I update to the latest API specification, and there are not breaking changes to the API, then Lily's generated source code doesn't break my application."
. Support _all_ OpenAPI features, including unusual things like matrix-style requests.

== Non-Goals

. Do not (yet) support other languages than Java. It's not clear that a Java-oriented AST will cleanly translate to another language target.
. Do not support too many options. Options become confusing to maintain -- prefer opinionated code that works for most people who are doing sensible things.

== Design

Lily is a layered API with "high-level" layers that orchestrate full requests using generated code and "low-level" layers that help the developer implement requests from scratch if necessary.

High-level layers always allow the developer to move into lower levels. This allows the developer to use the convenient high-level API _as much as possible_, then resort to the lower-level API (which could be the java.net.http API itself) only as necessary to work around missing features or undocumented API parameters.

Lily should make simple things easy, and complex things possible.

== Quick Tour

Lily is composed of four modules in the `modules` directory:

- `example` compiles the v3.0 petstore YAML as an example. Check out the generated-sources directory after a build to see what Lily generates, and the test directory to see example usage of the generated code.

- `lily-compiler-maven-plugin` is a teensy-weensy Maven plugin that reads configuration from the pom and hands it off to the compiler project. This is what the user adds to their projects to compile code.

- `lily-compiler` is responsible for reading an OAS document, translating it to an intermediary AST (abstract syntax tree), rendering the AST as source code, and finally saving source code to disc.

- `lily-http` defines classes to help create and receive HTTP requests, including RFC6570 encoders, deser implementations, and the UriTemplate. This is a dependency of generated source code and may also be used directly by users to work around Lily or OAS shortcomings.
