= Lily OAS-To-Java Compiler

Lily is a compiler that consumes OpenAPI (Swagger) specifications and produces Java source code.
It is intended to be an alternative to https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator], which at time of writing is the only option, and substantially more complete than Lily.

== Goals

. Generate java source code directly from an OAS document within a java build pipeline (e.g. integrated with Maven or Gradle).
. Support OAS v3.
. Target Java 17.
. Help end-users work around incorrect or incomplete schema specifications so that they can make progress while awaiting upstream fixes.
. [Tentative] Support customizable generated code, especially code which can leverage user-made JARs from unrelated projects.

== Non-Goals

. Do not (yet) support other languages than Java.
It's not clear that a Java-oriented AST will cleanly translate to another language target.
. Do not support too many options.
Options become confusing to maintain -- prefer opinionated code that works for most people who are doing sensible things.
. Do not support generate-and-check-in workflows.
Treat the OAS document as source code.

== Plan

We will follow an iterative approach from this point forward. To start, we define integration tests in the `it-project` module which demonstrate realistic use-cases based on hand-written java.net.http code. Once we have captured a use-case, we then add support to Lily which makes (part of) that case easier to implement, such as by adding support functions or new categories of code generation. After many iterations, these cases will largely be implemented using generated code and Lily support. At this point, Lily will be a mature solution.

== Design

Lily is a layered API with "high-level" layers that orchestrate full requests using generated code and "low-level" layers that help the developer implement requests from scratch if necessary. High-level layers always allow the developer to move into lower-levels so that the developer can override Lily to work around flaws in Lily, the upstream OAS, or other environmental issues.

Lily helps the developer where it is able, but gets out of the way when requested. With Lily, simple things are _easy_, and complex things are _possible_.

== Quick Tour

Lily is composed of three modules in the `modules` directory:

- `it-project` is an integration test project and living example of the compiler in action. The pom shows how to configure Lily in a maven build. The OAS shows what Lily supports. Test cases demonstrate where Lily lends support to HTTP clients. Check out the generated-sources directory under `target/` to see how it compiles OAS definitions.

- `lily-compiler-maven-plugin` is a teensy-weensy Maven plugin that reads configuration from the pom and hands it off to the compiler project.

- `lily-compiler` is responsible for reading an OAS document, translating it to an intermediary AST (abstract syntax tree), rendering the AST as source code, and finally saving source code to disc.

- `lily-http` defines classes to help use the java.net.http API. For example, this contains the JacksonBodyPublisher and JacksonBodyHandler for sending and receiving Json-serialized content.