openapi: 3.0.2
info:
  title: Example
  description: "An example OAS document to be compiled to Java source"
  version: 0.1.0
paths:
  /foo:
    get:
      operationId: getFoo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyObject'
          application/xml:
            schema:
              $ref: '#/components/schemas/MyObject'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MyObject'
      responses:
        "200":
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MyObject'
            application/json:
              schema:
                $ref: '#/components/schemas/MyObject'
        "400":
          description: Invalid ID supplied
        "404":
          description: MySimpleAlias not found
        "405":
          description: Validation exception
components:
  schemas:
    # An object with fields of every scalar type
    MyObject:
      type: object
      properties:
        a:
          type: boolean
        b:
          type: integer
        c:
          type: integer
          format: int32
        d:
          type: integer
          format: int64
        e:
          type: number
        f:
          type: number
          format: double
        g:
          type: number
          format: float
        h:
          type: string
        i:
          type: string
          format: password
        j:
          type: string
          format: byte
        k:
          type: string
          format: binary
        l:
          type: string
          format: date
        m:
          type: string
          format: date-time
    # An object with an in-lined object definition
    MyObject2:
      type: object
      properties:
        foo:
          type: object
          properties:
            bar:
              type: string
    # An alias for arrays of a scalar type.
    MyScalarAlias:
      type: string
    # An alias for arrays of a referenced type.
    MyRefArrayAlias:
      type: array
      items:
        $ref: "#/components/schemas/MyObject2"
    # An alias for arrays of a scalar type.
    MyScalarArrayAlias:
      type: array
      items:
        type: number
    # An alias for arrays of an in-lined object type
    MyInlineObjectArrayAlias:
      type: array
      items:
        type: object
        properties:
          foo:
            type: string
    # An alias for composite arrays of a referenced type
    MyCompositeRefArrayAlias:
      type: array
      items:
        type: array
        items:
          $ref: '#/components/schemas/MyObject2'
    # An alias for composite arrays of a scalar type
    MyCompositeScalarArrayAlias:
      type: array
      items:
        type: array
        items:
          type: string
    # An alias for composite arrays of an in-lined object type
    MyCompositeInlineObjectArrayAlias:
      type: array
      items:
        type: array
        items:
          type: object
          properties:
            foo:
              type: string
