openapi: 3.0.2
info:
  title: Example
  description: "An example OAS document to be compiled to Java source"
  version: 0.1.0
paths:
  /foo:
    get:
      operationId: getFoo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MySimpleAlias'
          application/xml:
            schema:
              $ref: '#/components/schemas/MySimpleAlias'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MySimpleAlias'
      responses:
        "200":
          description: Successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/MySimpleAlias'
            application/json:
              schema:
                $ref: '#/components/schemas/MySimpleAlias'
        "400":
          description: Invalid ID supplied
        "404":
          description: MySimpleAlias not found
        "405":
          description: Validation exception
components:
  schemas:
    # An object with fields of every standard type
    MyObject:
      type: object
      properties:
        a:
          type: boolean
        b:
          type: integer
        c:
          type: integer
          format: int32
        d:
          type: integer
          format: int64
        e:
          type: number
        f:
          type: number
          format: double
        g:
          type: number
          format: float
        h:
          type: string
        i:
          type: string
          format: password
        j:
          type: string
          format: byte
        k:
          type: string
          format: binary
        l:
          type: string
          format: date
        m:
          type: string
          format: date-time
    # An object with an in-line object definition
    MyObject2:
      type: object
      properties:
        foo:
          type: object
          properties:
            bar:
              type: string
    # An alias for the simple/standard String type.
    MySimpleAlias:
      type: string
    # An alias for arrays of numbers.
    MyArrayAlias:
      type: array
      items:
        type: number
    # An alias for arrays of the in-lined type
    MyArrayAlias2:
      type: array
      items:
        type: object
        properties:
          foo:
            type: string
          bar:
            type: integer