openapi: 3.0.2
info:
  title: Example
  description: "An example OAS document to be compiled to Java source"
  version: 0.1.0
paths:
  /foo/{foo}:
    post:
      operationId: 'postFoo'
      parameters:
        - name: foo
          in: path
          required: true
          schema:
            type: string
        - name: My-Header
          in: header
          required: true
          schema:
            type: string
        - name: queryOption
          in: query
          required: true
          schema:
            type: boolean
        - name: MyCookie
          in: cookie
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostFooBody'
      responses:
        "200":
          description: "Success!"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostFooResponse'
components:
  schemas:
    PostFooBody:
      type: object
      properties:
        bar:
          type: string
    PostFooResponse:
      type: object
      properties:
        baz:
          type: string