name: release
on:
  release:
    types:
      - created
jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      is_maven_release: ${{ steps.check-tag.outputs.is_maven_release }}
      version: ${{ steps.check-tag.outputs.version }}
    steps:
      - name: check tag (${{ github.event.release.tag_name }})
        id: check-tag
        run: |
          # parse the version out of VALUE
          if [[ "${{ github.event.release.tag_name }}" =~v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            TAG=${VALUE#*v}
            echo "::set-output name=is_maven_release::true"
            echo "::set-output name=tag::$TAG"
          else
            echo "::set-output name=is_maven_release::false"
          fi
  release:
    name: 'release'
    needs: [check_tag]
    if: needs.check_tag.outputs.is_maven_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: |
          echo "Would deploy ${{ needs.check_tag.outputs.tag }}"
#          ./mvnw deploy \
#            --batch-mode \
#            -Drevision=$RELEASE_VERSION
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}