name: release
on:
  release:
    types:
      - created
jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      is_maven_release: ${{ steps.check-tag.outputs.is_maven_release }}
    steps:
      - name: check tag ${{ github.ref }}
        id: check-tag
        run: |
          if [[${{ github.ref }} =~ refs\/tags\/release\/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=is_maven_release::true"
          else
            echo "::set-output name=is_maven_release::false"
          fi
  release:
    name: 'release'
    needs: [check_tag]
    if: needs.check_tag.outputs.is_maven_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Extract version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Publish package
        run: |
          echo "Would deploy $RELEASE_VERSION"
#          ./mvnw deploy \
#            --batch-mode \
#            -Drevision=$RELEASE_VERSION
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}